### ISSUE TITLE
Consider check-parameters option of no-duplicate-variable

### ISSUE THREAD

**Issue by saneyuki** [voyagegroup/tslint-config-fluct#22]
- Follow up https://github.com/voyagegroup/tslint-config-fluct/pull/20
- https://github.com/palantir/tslint/releases/tag/5.4.0

**Comment by kanufy** [comment]
```js
export function hoge(x: number){
    console.log(x);
    let x = 1;
    x = x + x;
    console.log(x);
}
```

とかだとlintでおこられないけどcompilerのエラーとなるのでこのオプションではみてなくて
このオプションでlintにて怒られ発生するのは

```js
export function cal(x: number){
    console.log(x);
    var x = 1;
    x = x + x;
    console.log(x);
};
```

みたいなときになるけど、（compilerには怒られない）
下記みたいに letかconstつかってねっていう怒られが発生するので

```
WARNING:  Duplicate variable: 'x'
ERROR: Forbidden 'var' keyword, use 'let' or 'const' instead
ERROR: Unnecessary semicolon
```

結果letとかconst使うとこのオプションの意味なさなそうだし
あってもなくても変わらないような気がした。

**Comment by saneyuki** [comment]
Decision: Don't add.
