### ISSUE TITLE
Consider as-needed option of curly rule

### ISSUE THREAD

**Issue by saneyuki** [voyagegroup/tslint-config-fluct#23]
- Follow up https://github.com/voyagegroup/tslint-config-fluct/pull/20
- https://github.com/palantir/tslint/releases/tag/5.4.0

**Comment by kanufy** [comment]
一行であっても明示的にcurlyついてて欲しい派なので
`as-needed` はいらないと思いました

**Comment by saneyuki** [comment]
Decision: Don't add.
