### ISSUE TITLE
Consider ignore-static option of no-unbound-method

### ISSUE THREAD

**Issue by saneyuki** [voyagegroup/tslint-config-fluct#24]
- Follow up https://github.com/voyagegroup/tslint-config-fluct/pull/20
- https://github.com/palantir/tslint/releases/tag/5.4.0

**Comment by kanufy** [comment]
typecheck系のruleについては現在有効になっていなくて
必要かどうか判断できかねるので今のところパスしたい気持ちがあります

**Comment by saneyuki** [comment]
Decision: postpone to https://github.com/voyagegroup/tslint-config-fluct/issues/7
