### ISSUE TITLE
Consider allow-boolean-or-undefined of strict-boolean-expressions rule

### ISSUE THREAD

**Issue by saneyuki** [voyagegroup/tslint-config-fluct#25]
- Follow up https://github.com/voyagegroup/tslint-config-fluct/pull/20
- https://github.com/palantir/tslint/releases/tag/5.4.0

**Comment by kanufy** [comment]
#24 とおなじくtypecheck系のruleについては現在有効になっていなくて
必要かどうか判断できかねるので今のところパスしたい気持ちがあります

**Comment by saneyuki** [comment]
Decision: postpone to https://github.com/voyagegroup/tslint-config-fluct/issues/7
