### ISSUE TITLE
Update tslint 5.5=>5.6

### ISSUE THREAD

**Issue by kanufy** [voyagegroup/tslint-config-fluct#31]
## リリースノート
https://github.com/palantir/tslint/releases

新しいruleがいくつか増えてるのでみる

**Comment by kanufy** [comment]
## new rules
- [no-duplicate-imports](https://palantir.github.io/tslint/rules/no-duplicate-imports/)
  - 重複するimportは不可
  - eslintにも同じruleはあり、[eslint-config-fluct](https://github.com/voyagegroup/eslint-config-fluct) では `'no-duplicate-imports': 1` としている

```ts
// Bad
import { hoge } from 'piyo/foo'
import { fuga } from 'piyo/foo'

// OK
import { hoge, fuga } from 'piyo/foo'
```

eslintの設定と同じくwarnでよさそう

- [no-submodule-imports](https://palantir.github.io/tslint/rules/no-submodule-imports/)
  - submoduleのimportはホワイトリスト形式でしか許可しない

```ts
// Bad
import { hoge } from 'piyo/foo'

// OK
import { hoge } from 'piyo'
import { bose } from 'bar/baz'

// rule
"no-submodule-imports": [true, "bar"]
```

>Submodules of some packages are treated as private APIs and the import paths may change without deprecation periods. 

まあなるほどなあという感じではあるんだけどどうするのがいいかなー。
設定したとすると、ホワイトリストは各プロジェクトで列挙するという形になるけど
ライブラリのサブモジュールimport追加するたびにリスト追加していかないとで、だるいかなという印象がある。
たとえば `office-ui-fabric-react` とかは結構サブモジュールでimportしているし。
ライブラリ少ないうちはいいんだけど増えてくるとなあ、みたいな。

-  [space-within-parens](https://palantir.github.io/tslint/rules/space-within-parens/)
  - 括弧などの挿入語句内のspaceを必要とする/不必要とする

```ts
// Bad
constructor() { }
           
console.log('piyo')
                 
a.map((v)=>{
    console.log(v);
});

// OK
console.log( 'piyo' )


// rule
"space-within-parens": [true, 1]
```

ちょっと現実的じゃないかな。
arrowfuncとかそのへんいい感じにできるoptionがあればまだいいけど
spaceの数を指定するoptionしかないしいらなさそう。


## new options
- [no-shadowed-variable](https://palantir.github.io/tslint/rules/no-shadowed-variable/)
  - 包含関係での同じ名前の変数宣言を無効にする
  - let's you optionally ignore certain kinds of declarations

これそもそもrule自体が設定されてなかったから改めてみてみたけど、
rxjsだとしっかりひっかかり

```ts
a.combineLatest(b, (b, a) => ({ b, a }));
```

みたいなのはアウトになるので使いづらい
falseにしておいてもいいんじゃないかなと思ったりするんだけどどうでしょう。

- [prefer-conditional-expression](https://palantir.github.io/tslint/rules/prefer-conditional-expression/)
  - adds check-else-if
 
このオプションあっても現状のまま( `"prefer-conditional-expression": false,` )でよさそうかな
ちなみにこのrule自体に変更があって、

> [rule-change] prefer-conditional-expression: ignore if-else-if by default. Use the new "check-else-if" option to check nested if statements

とのことだけど、つかってない(false)ので問題ないかと。


---

@nekoya ざっとチェックしてみたけどどうでしょうか？ 
（new-fixerについては必要ないかとおもうので省略してます）

**Comment by saneyuki** [comment]
> no-submodule-imports

I think this should not be enabled. What your said is right. It's too stupid to enforce to configure in for each project. This feature should be opt-in.

> space-within-parens

You are right. [eslint-config-fluct](https://github.com/voyagegroup/eslint-config-fluct/blob/191387c37f376869d792732e005613b9bd42d011/config/eslintrc_core.js#L337-L348) also disable or use as warning similar rules. It's misc issues.

> no-shadowed-variable

eslint-config-fluct disables this:  https://github.com/voyagegroup/eslint-config-fluct/blob/191387c37f376869d792732e005613b9bd42d011/config/eslintrc_core.js#L155

**Comment by nekoya** [comment]
全面的によさそう

**Comment by nekoya** [comment]
description改めてよく見たら`no-shadowed-variable`がnew optionsになってるけど、ルールの追加ですね。まぁ、わかる。

**Comment by kanufy** [comment]
リリースノート的には new optionなんですが
tslint-config-fluct的には追加してなかったruleだったので結果的にそうですねｗ
